name       : perl-encode-hanextra
version    : '0.23'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/A/AU/AUDREYT/Encode-HanExtra-0.23.tar.gz : 1fd4b06cada70858003af153f94c863b3b95f2e3d03ba18d0451a81d51db443a
license    : MIT
component  : programming.perl
summary    : Encode::HanExtra - Extra sets of Chinese encodings
description: |
    Encode::HanExtra - Extra sets of Chinese encodings
builddeps  :
    - perl
setup      : |
    export PERL_USE_UNSAFE_INC=1
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
